### ISSUE TITLE
Kibana import errors due backwards incompatibility

### ISSUE THREAD

**Issue by nhairs-finder** [domainaware/parsedmarc#141]
Hi There,
I've got a couple of errors to report based on the [latest (95477bb)](https://github.com/domainaware/parsedmarc/blob/95477bb818c72b9ddcad7b2453bb82ec6a6d78a2/kibana/export.ndjson) `export.ndjson`.

These errors appear to be mostly related to backwards incompatibilities between Kibana versions. Not expecting it be fixed, mostly leaving this here in case others encounter similar issues and need workarounds.

Discovered using Kibana version `7.4.0`.

### Error 1: Unexpected object

**Symptoms**
Request will eventually timeout and this message will be shown. There is no other info provided in the UI or the network request.
![image](https://user-images.githubusercontent.com/55079540/73240245-822b7a80-41f2-11ea-8a74-03c4413c8ef3.png)

In the Kibana log you will find a message like:
```
TypeError: Cannot read property 'title' of undefined
    at obj (/opt/kibana/src/core/server/saved_objects/import/collect_saved_objects.js:45:29)
    at Transform.transform [as _transform] (/opt/kibana/src/legacy/utils/streams/filter_stream.js:33:33)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Transform.Writable.write (_stream_writable.js:294:11)
    at Transform.ondata (_stream_readable.js:667:20)
    at Transform.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Transform.Readable.push (_stream_readable.js:220:10)
    at Transform.push (_stream_transform.js:151:32)
    at Transform.afterTransform (_stream_transform.js:92:10)
    at Transform.transform [as _transform] (/opt/kibana/src/core/server/saved_objects/import/create_limit_stream.js:43:7)
    at Transform._read (_stream_transform.js:190:10)
```

**Issue**
Older versions of Kibana do not handle the metadata line

**Work Around**
Can remove the following line:
`{"exportedCount":22,"missingRefCount":0,"missingReferences":[]}`

### Error 2: Kibana Version
**Symptoms**
UI will display following error:
![image](https://user-images.githubusercontent.com/55079540/73240245-822b7a80-41f2-11ea-8a74-03c4413c8ef3.png)

HTTP request will return the following:
```
{
  "statusCode": 422,
  "error": "Unprocessable Entity",
  "message": "Document \"085eaa30-2870-11e8-b8b2-15742da3055c\" has property \"visualization\" which belongs to a more recent version of Kibana (7.4.2)."
}
```

**Issue**
Kibana will reject imports where the data was exported from a newer version of Kibana.

**Work Around**
Use [older version (e054bc7)](https://github.com/domainaware/parsedmarc/blob/e054bc7cbea88700d8a25be97d5c8ef0dcb70b2d/kibana/export.ndjson) of `export.ndjson`.

It may be possible to simply change the version number in the JSON, but may encounter other bugs due to backwards incompatible exported JSON.

**Comment by seanthegeek** [comment]
Thanks for the documentation
