### ISSUE TITLE
Problem when trying to create elasticsearch indexes

### ISSUE THREAD

**Issue by flobiree** [domainaware/parsedmarc#15]
Hi,

I'm using parsedmarc without difficulties, until today when I tried to connect it with elasticsearch/kibana, following the documentation.
Ran with parsedmarc -o $reportdir -H $host -u $user -p $pass --save-aggregate -E 127.0.0.1:9200, the output is:

Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 11, in <module>
    load_entry_point('parsedmarc==4.1.0', 'console_scripts', 'parsedmarc')()
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/cli.py", line 194, in _main
    elastic.create_indexes([es_aggregate_index, es_forensic_index])
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/elastic.py", line 187, in create_indexes
    index.put_settings(settings)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch_dsl/index.py", line 430, in put_settings
    return self._get_connection(using).indices.put_settings(index=self._name, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: put_settings() missing 1 required positional argument: 'body'

Any idea on how to solve this?

**Comment by seanthegeek** [comment]
@flobiree Sorry about that! fixed in 4.1.3 :)

**Comment by flobiree** [comment]
Thank you, it's working well now!
(and thanks for the quick fix!)
