### ISSUE TITLE
Fresh install on Ubuntu  -> "undefined symbol: PyUnicode_New"

### ISSUE THREAD

**Issue by akkerkid** [domainaware/parsedmarc#180]
I've got a fresh install of parsedmarc on a fresh ubuntu. Followed the instructions exactly but ended up here:

Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 5, in <module>
    from parsedmarc.cli import _main
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/__init__.py", line 32, in <module>
    from parsedmarc.utils import get_base_domain, get_ip_address_info
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/utils.py", line 20, in <module>
    import dateparser
  File "/opt/venvs/parsedmarc/site-packages/dateparser/__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "/opt/venvs/parsedmarc/site-packages/dateparser/date.py", line 9, in <module>
    import regex as re
  File "/opt/venvs/parsedmarc/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/opt/venvs/parsedmarc/site-packages/regex/regex.py", line 404, in <module>
    import regex._regex_core as _regex_core
  File "/opt/venvs/parsedmarc/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ImportError: /opt/venvs/parsedmarc/site-packages/regex/_regex.pypy3-72-x86_64-linux-gnu.so: undefined symbol: PyUnicode_New

**Comment by vppencilsharpener** [comment]
Did you ever find a resolution to this problem?

**Comment by akkerkid** [comment]
Nope. I gave up.  I may try again in the future and/or with a different
distro...

**Comment by vppencilsharpener** [comment]
Yep. I'm getting the same error with 18.04 and 20.04 following the instructions here: https://github.com/domainaware/parsedmarc/blob/master/docs/index.rst

**Comment by vppencilsharpener** [comment]
I tried 2 different version of pypy3 (3.6 and 3.7), neither of which worked. 

I then tried to run it outside of the pypy3 environment and was able to make it work. 
I think the problem is related to the pypy3 environment.

**Comment by seanthegeek** [comment]
This looks like it was caused by a bug in the regex pypi package at one point. I was able to install from a fresh virtualenv just now on both Debian and Ubuntu. Please try upgrading that package within your virtualenv by running pip3 install -U regex
