### ISSUE TITLE
mail parser issue

### ISSUE THREAD

**Issue by triplephteven** [domainaware/parsedmarc#196]
Hi there,

Since my disk storage was full I have issues with the service to pick up emails. This is the error:

`Nov 01 22:03:01 skyhost systemd[1]: Started parsedmarc mailbox watcher.
Nov 01 22:03:01 skyhost systemd[1]: Stopped parsedmarc mailbox watcher.
Nov 01 22:02:00 skyhost systemd[1]: parsedmarc.service: Failed with result 'exit-code'.
Nov 01 22:02:00 skyhost systemd[1]: parsedmarc.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 22:02:00 skyhost parsedmarc[3545]: pkg_resources.DistributionNotFound: The 'six==1.13.0' distribution was not found and is required by mailsuite
Nov 01 22:02:00 skyhost parsedmarc[3545]:     raise DistributionNotFound(req, requirers)
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
Nov 01 22:02:00 skyhost parsedmarc[3545]:     dists = ws.resolve(reqs, Environment())
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
Nov 01 22:02:00 skyhost parsedmarc[3545]:     return cls._build_from_requirements(__requires__)
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
Nov 01 22:02:00 skyhost parsedmarc[3545]:     working_set = WorkingSet._build_master()
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
Nov 01 22:02:00 skyhost parsedmarc[3545]:     f(*args, **kwargs)
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
Nov 01 22:02:00 skyhost parsedmarc[3545]:     @_call_aside
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
Nov 01 22:02:00 skyhost parsedmarc[3545]:     from pkg_resources import load_entry_point
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/local/bin/parsedmarc", line 6, in <module>
Nov 01 22:02:00 skyhost parsedmarc[3545]: Traceback (most recent call last):
Nov 01 22:02:00 skyhost parsedmarc[3545]: During handling of the above exception, another exception occurred:
Nov 01 22:02:00 skyhost parsedmarc[3545]: pkg_resources.ContextualVersionConflict: (six 1.15.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('six==1.13.0'), {'mailsuite'})
Nov 01 22:02:00 skyhost parsedmarc[3545]:     raise VersionConflict(dist, req).with_context(dependent_req)
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
Nov 01 22:02:00 skyhost parsedmarc[3545]:     needed = self.resolve(parse_requirements(requirements))
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
Nov 01 22:02:00 skyhost parsedmarc[3545]:     ws.require(__requires__)
Nov 01 22:02:00 skyhost parsedmarc[3545]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
`

**Comment by seanthegeek** [comment]
This was caused by the old `mailsuite` `six==1.13.0` pin conflicting with a newer system `six`. The `six` dependency was removed entirely in parsedmarc 6.12.0 / mailsuite 1.6.1, so this can't recur on any supported version. Closing; please reinstall in a clean venv if you still see `pkg_resources` errors.

---
🤖 Triaged and closed by [Claude Code](https://claude.com/claude-code) at the maintainer's request.
