### ISSUE TITLE
Crash on IMAP disconnect

### ISSUE THREAD

**Issue by Olen** [domainaware/parsedmarc#211]
The IMAP-server was temporarily unavailable for a few minutes and this caused a crash:

```
Traceback (most recent call last):                               
  File "/usr/local/lib/python3.7/site-packages/mailsuite/imap.py", line 75, in _start_idle                               
    self.idle_done()                               
  File "/usr/local/lib/python3.7/site-packages/imapclient/imapclient.py", line 175, in wrapper                                                                                                                     
    return func(client, *args, **kwargs)                                                                 
  File "/usr/local/lib/python3.7/site-packages/imapclient/imapclient.py", line 974, in idle_done                                                                                                                   
    self._imap.send(b"DONE\r\n")                                                                         
  File "/usr/local/lib/python3.7/site-packages/imapclient/tls.py", line 62, in send                                                                                                                                
    self.sock.sendall(data)                                                                              
  File "/usr/local/lib/python3.7/ssl.py", line 1034, in sendall           
    v = self.send(byte_view[count:])                                                                     
  File "/usr/local/lib/python3.7/ssl.py", line 1003, in send              
    return self._sslobj.write(data)                                                                      
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:2423)                                                                                                                                     
                     
During handling of the above exception, another exception occurred:                                                                                                                                                
                     
Traceback (most recent call last):                                                                       
  File "/usr/local/bin/parsedmarc", line 8, in <module>                    
    sys.exit(_main())                                                                                    
  File "/usr/local/lib/python3.7/site-packages/parsedmarc/cli.py", line 665, in _main                                                                                                                              
    strip_attachment_payloads=sa)                                                                        
  File "/usr/local/lib/python3.7/site-packages/parsedmarc/__init__.py", line 1233, in watch_inbox                                                                                                                  
    idle_timeout=idle_timeout)                                                                            
  File "/usr/local/lib/python3.7/site-packages/mailsuite/imap.py", line 192, in __init__                                                                                                                           
    self._start_idle(idle_callback, idle_timeout=idle_timeout)            
  File "/usr/local/lib/python3.7/site-packages/mailsuite/imap.py", line 90, in _start_idle                                                                                                                         
    self.reset_connection()                                                                              
  File "/usr/local/lib/python3.7/site-packages/mailsuite/imap.py", line 212, in reset_connection                                                                                                                   
    idle_timeout=self._init_args["idle_timeout"],                         
  File "/usr/local/lib/python3.7/site-packages/mailsuite/imap.py", line 148, in __init__                                                                                                                           
    timeout=timeout)                                                                                            
  File "/usr/local/lib/python3.7/site-packages/imapclient/imapclient.py", line 284, in __init__                                                                                                                    
    self._imap = self._create_IMAP4()                                                                           
  File "/usr/local/lib/python3.7/site-packages/imapclient/imapclient.py", line 325, in _create_IMAP4                                                                                                               
    connect_timeout,                                                                                     
  File "/usr/local/lib/python3.7/site-packages/imapclient/tls.py", line 44, in __init__                                                                                                                            
    imaplib.IMAP4.__init__(self, host, port)                              
  File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__                                                                                                                                                
    self.open(host, port)                                                                                
  File "/usr/local/lib/python3.7/site-packages/imapclient/tls.py", line 52, in open                                                                                                                                
    self.sock = wrap_socket(sock, self.ssl_context, host)                 
  File "/usr/local/lib/python3.7/site-packages/imapclient/tls.py", line 32, in wrap_socket                                                                                                                         
    return ssl_context.wrap_socket(sock, server_hostname=host)            
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket                                                                                                                                                 
    session=session                                                                                      
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create            
    self.do_handshake()                                                                                  
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake                                                                                                                                               
    self._sslobj.do_handshake()                                                                          
ConnectionResetError: [Errno 104] Connection reset by peer                
```

**Comment by seanthegeek** [comment]
Closing as fixed — verified empirically today against current `master` (10.2.4).

**Root cause:** In the parsedmarc 6.x/7.x era, `watch_inbox()` called `mailsuite.imap.IMAPClient` directly. When the IDLE loop detected a dropped connection it called `reset_connection()`, but if the server was still unreachable, the reconnect attempt itself raised (the `ConnectionResetError` in the traceback above). That second exception escaped the IDLE loop's `except` handler, propagated through `watch_inbox()`, and killed the process.

**Fix:** parsedmarc **8.0.0** (April 2022; first non-yanked release **8.0.3**) introduced the `MailboxConnection` abstraction, whose `IMAPConnection.watch()` wraps the entire IDLE session in a retry loop that catches all connection errors, logs a warning, sleeps, and rebuilds the connection from scratch — indefinitely, until the server comes back. Since **9.11.0** (#741) that layer lives upstream in `mailsuite.mailbox`, so the resilience is now handled by mailsuite, where it belongs.

**Verification:** Ran parsedmarc 10.2.4 (mailsuite 2.2.2) in watch mode against a Dovecot 2.4.4 container over IMAPS, then stopped the container for ~2 minutes. The log shows the exact failure sequence from this issue — connection reset caught, reconnect attempted, reconnect itself failing with an SSL EOF — now handled instead of fatal:

```
DEBUG:imap.py:IMAP error: Connection reset
 INFO:imap.py:Reconnecting to IMAP
WARNING:imap.py:IMAP connection error. [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol. Reconnecting...
WARNING:imap.py:IMAP connection error. [Errno 111] Connection refused. Reconnecting...   (repeated every check_timeout)
```

After the container restarted, parsedmarc reconnected on its own, found a newly delivered report, parsed it, and archived it — same PID throughout, no crash.
