### ISSUE TITLE
ERROR:cli.py:615:IMAP Error: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Idriel** [domainaware/parsedmarc#221]
DEBUG:__init__.py:1071:Found 3900 messages in DMARC
DEBUG:__init__.py:1075:Processing message 1 of 3900: UID 35273
ERROR:cli.py:615:IMAP Error: 'NoneType' object has no attribute 'decode'

Version: 6.12.0

**Comment by Idriel** [comment]
`Traceback (most recent call last):
  File "/opt/pypy/bin/parsedmarc", line 8, in <module>
    sys.exit(_main())
  File "/opt/pypy/site-packages/parsedmarc/cli.py", line 665, in _main
    strip_attachment_payloads=sa)
  File "/opt/pypy/site-packages/parsedmarc/__init__.py", line 1233, in watch_inbox
    idle_timeout=idle_timeout)
  File "/opt/pypy/site-packages/mailsuite/imap.py", line 192, in __init__
    self._start_idle(idle_callback, idle_timeout=idle_timeout)
  File "/opt/pypy/site-packages/mailsuite/imap.py", line 83, in _start_idle
    idle_callback(self)
  File "/opt/pypy/site-packages/parsedmarc/__init__.py", line 1224, in idle_callback
    strip_attachment_payloads=sa)
  File "/opt/pypy/site-packages/parsedmarc/__init__.py", line 1085, in get_dmarc_reports_from_inbox
    strip_attachment_payloads=sa)
  File "/opt/pypy/site-packages/parsedmarc/__init__.py", line 816, in parse_report_email
    parallel=parallel)
  File "/opt/pypy/site-packages/parsedmarc/__init__.py", line 409, in parse_aggregate_report_file
    parallel=parallel)
  File "/opt/pypy/site-packages/parsedmarc/__init__.py", line 228, in parse_aggregate_report_xml
    xml = etree.tostring(tree).decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
`

**Comment by jeffrysleddens** [comment]
We got this exact error when we tried to feed a TLS report to parsedmarc by mistake.

**Comment by snhel5** [comment]
I just installed it on my mail server and am running into the same error.

0it [00:00, ?it/s]
   DEBUG:__init__.py:1071:Found 1 messages in INBOX
   DEBUG:__init__.py:1075:Processing message 1 of 1: UID 1
   ERROR:cli.py:615:IMAP Error: 'NoneType' object has no attribute 'decode'

The mailbox is newley created specificly for this.
Only report in it  is from ParseDMARC itself.

Version is same 6.12

**Comment by mwander** [comment]
Workaround:

Change `__init__.py:218 (def parse_aggregate_report_xml)` from this:
```
xml = etree.tostring(tree).decode('utf-8')
```

to this:
```
s = etree.tostring(tree)
xml = '' if s is None else s.decode('utf-8')
```
