### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by knightian** [domainaware/parsedmarc#251]
After the latest merge train when starting parsedmarc I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 5, in <module>
    from parsedmarc.cli import _main
  File "/usr/local/lib/python3.8/dist-packages/parsedmarc/cli.py", line 740
    offline=opts.offline,
    ^
SyntaxError: invalid syntax
```

**Comment by knightian** [comment]
@seanthegeek see https://github.com/domainaware/parsedmarc/pull/252 for fix
