### ISSUE TITLE
INFO:cli.py:601:Starting dmarcparse; AttributeError: 'Namespace' object has no attribute 'ip_db_path'

### ISSUE THREAD

**Issue by leonardo0014** [domainaware/parsedmarc#286]
It seems to me that the "ip_db_path" variable introduced with version 7.1.1 has no initial base value set. 
Shouldn't the parameter be optional?

Example:
```
parsedmarc --debug --verbose --offline /opt/files/2020/02/enbw.com\!firma.org\!1582671603\!1582758002.xml.gz
    INFO:cli.py:601:Starting dmarcparse
Traceback (most recent call last):
  File "/usr/bin/parsedmarc", line 8, in <module>
    sys.exit(_main())
  File "/usr/lib/python3.6/site-packages/parsedmarc/cli.py", line 664, in _main
    repeat(opts.ip_db_path),
AttributeError: 'Namespace' object has no attribute 'ip_db_path'
```

**Comment by taladar** [comment]
I am running into the same problem.
