### ISSUE TITLE
Error Importing to Elastic Search

### ISSUE THREAD

**Issue by kingbutter** [domainaware/parsedmarc#31]
Fresh Install, Ubuntu 18.04.1

Python 3.6.6
parsedmarc 4.3.8
elasticsearch: 6.4.3

Reports seem to grab okay via IMAP, but fail when trying to import to elasticsearch.

Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 11, in <module>
    sys.exit(_main())
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/cli.py", line 333, in _main
    process_reports(results)
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/cli.py", line 42, in process_reports
    report, index=es_aggregate_index)
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/elastic.py", line 292, in save_aggregate_report_to_elasticsearch
    agg_doc.save()
  File "/opt/venvs/parsedmarc/site-packages/parsedmarc/elastic.py", line 88, in save
    return super().save(** kwargs)
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/document.py", line 383, in save
    self.full_clean()
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/utils.py", line 444, in full_clean
    self.clean_fields()
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/utils.py", line 430, in clean_fields
    data = field.clean(data)
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/field.py", line 207, in clean
    data.full_clean()
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/utils.py", line 444, in full_clean
    self.clean_fields()
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/utils.py", line 430, in clean_fields
    data = field.clean(data)
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/field.py", line 95, in clean
    data = self.deserialize(data)
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/field.py", line 91, in deserialize
    return self._deserialize(data)
  File "/opt/venvs/parsedmarc/site-packages/elasticsearch_dsl/field.py", line 314, in _deserialize
    return int(data)
ValueError: invalid literal for int() with base 10: '0:1:d:s'

**Comment by seanthegeek** [comment]
Can you forward some of the aggregate emails to me for debugging?

seanpw@pm.me

**Comment by seanthegeek** [comment]
Thanks for the samples, this looks like a bug in the elasticsearch-dsl python package.

I've created an issue there

https://github.com/elastic/elasticsearch-dsl-py/issues/1055

**Comment by kingbutter** [comment]
Thanks

**Comment by seanthegeek** [comment]
This has been fixed in `parsedmarc` 5.0.0.

**Warning**: Re-importing `kibana_saved_objects.json` in Kibana [is required](https://domainaware.github.io/parsedmarc/#upgrading-kibana-index-patterns) when upgrading to this version!
