### ISSUE TITLE
IMAP password cannot start with %

### ISSUE THREAD

**Issue by bigon** [domainaware/parsedmarc#314]
Hello,

My IMAP passwords starts with a `%` and apparently parsedmarc is not happy:

```
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.9/dist-packages/parsedmarc/cli.py", line 424, in _main
    opts.imap_password = imap_config["password"]
  File "/usr/lib/python3.9/configparser.py", line 1255, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib/python3.9/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib/python3.9/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.9/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%foo'
```

That could be a problem with other parameter as well

**Comment by seanthegeek** [comment]
Try escaping the `%` by putting a `\` before it. That should work. Let me know if it does, and I'll add a note to the documentation.

**Comment by bigon** [comment]
No, it's giving the same error

**Comment by seanthegeek** [comment]
Try `%%` instead.
