### ISSUE TITLE
Error while launch parsedmarc

### ISSUE THREAD

**Issue by ASLLR** [domainaware/parsedmarc#382]
Hi everyone, i'm stuck with an error when i lauch parsedemarc. 

I use a venv to launch this command : parsedmarc -c parsedmarc.ini 

And this is the errors that result : 

sorting messages [...] and : 
`
Traceback (most recent call last):
  File "[MYSERVERLOC]/dmarc-parser/venv3/bin/parsedmarc", line 8, in <module>
    sys.exit(_main())
  File "[MYSERVERLOC]/dmarc-parser/venv3/lib/python3.9/site-packages/parsedmarc/cli.py", line 975, in _main
    process_reports(results)
  File "[MYSERVERLOC]/dmarc-parser/venv3/lib/python3.9/site-packages/parsedmarc/cli.py", line 81, in process_reports
    save_output(results, output_directory=opts.output,
  File "[MYSERVERLOC]/dmarc-parser/venv3/lib/python3.9/site-packages/parsedmarc/__init__.py", line 1325, in save_output
    append_json(os.path.join(output_directory, aggregate_json_filename),
  File "[MYSERVERLOC]/dmarc-parser/venv3/lib/python3.9/site-packages/parsedmarc/__init__.py", line 1265, in append_json
    with open(filename, "r+", newline="\n", encoding="utf-8") as output:
FileNotFoundError: [Errno 2] No such file or directory: '[MYSERVEROUTPUT]/parsedmarc/aggregate.json'
`

I use the documentation : https://domainaware.github.io/parsedmarc/ to build the parsedmarc.ini. 

You can help me ?

Thank in advance,

**Comment by Pascal76** [comment]
https://github.com/domainaware/parsedmarc/issues/358
https://github.com/domainaware/parsedmarc/issues/355

**Comment by ASLLR** [comment]
Hi @Pascal76, Thank you for your answer and sorry for the dupplicate issue. Mine is similar to 358 because i've not a smtp configured like the 355. 

Best regards

**Comment by Pascal76** [comment]
up
