### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Idriel** [domainaware/parsedmarc#424]
Run inside Docker gives me this error

RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.9/site-packages/parsedmarc/cli.py", line 898, in _main
    pool = Pool(opts.n_procs, initializer=init, initargs=(counter,))
  File "/usr/local/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 232, in __init__
    self._worker_handler.start()
  File "/usr/local/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by Idriel** [comment]
Looks like Docker upgrade solved this
