### ISSUE TITLE
ERROR:cli.py:1053:Failed to email results

### ISSUE THREAD

**Issue by MatthK** [domainaware/parsedmarc#431]
I recently migrated my docker installation from one machine to another. Since then, I do get the following errors in the parsedmarc container.

```
   ERROR:cli.py:1053:Failed to email results
Traceback (most recent call last):
  File "/opt/pypy/lib/pypy3.10/site-packages/mailsuite/smtp.py", line 61, in send_email
    server = smtplib.SMTP(host, port=port)
  File "/opt/pypy/lib/pypy3.10/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/pypy/lib/pypy3.10/smtplib.py", line 343, in connect
    (code, msg) = self.getreply()
  File "/opt/pypy/lib/pypy3.10/smtplib.py", line 405, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/cli.py", line 1047, in _main
    email_results(results, opts.smtp_host, opts.smtp_from,
  File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/__init__.py", line 1464, in email_results
    send_email(host, mail_from, mail_to, message_cc=mail_cc,
  File "/opt/pypy/lib/pypy3.10/site-packages/mailsuite/smtp.py", line 83, in send_email
    raise SMTPError(error)
mailsuite.smtp.SMTPError: Connection unexpectedly closed
```

I'm not quite sure where that comes from. I didn't change the parsedmarc.ini file, so all the settings should be the same.

**Comment by MatthK** [comment]
Thanks for the prompt reply. I do understand that, yes. However what I am wondering is as to why it doesn't work anymore. 

As I said, I have not updated the config file when I moved the docker-compose from one server to the other. And I also wonder, if there is some log file or something where I can find more details as to why the connection gets closed. On the mail server side I can't see much despite using full debug mode. All I got there is a similar message.

```
09/18/23 12:14:55	Couldn't decrypt, error 80090330
09/18/23 12:14:55	ME-I0070: (recv) socket [1184] was gracefully closed during [AUTH] command by the remote client x.x.40.149.
09/18/23 12:14:55	[RECV FAILURE DATASTART SOCKET=1184 STATUS=0 APPARENTSIZE=22]ZmFtaWx5MTAxMTIzNDU=

[RECV DATAEND SOCKET=1184]
09/18/23 12:14:55	ME-I0074: [1184] (Debug) End of conversation
09/18/23 12:14:56	[1140] SSL recv failed: 10060.
09/18/23 12:14:56	[1140] SSL_Handshake negotiation failed
09/18/23 12:14:56	ME-E0xxx: [1140] SSL Handshake failed. Closing connection.
09/18/23 12:14:56	[RECV SUCCESS DATASTART SOCKET=1256 STATUS=12 APPARENTSIZE=12]AUTH LOGIN
```

The server is not offering any "older" protocolls like SSL3 or TLS1.1. It only offers TLS1.2 and receives an overall B rating on www.ssllabs.com. The Key Exchange is only amber, as the server is an older Windows machine that doesn't support newer cipher suites.

What is the minimum requirement from parsedmarc to connect?

**Comment by seanthegeek** [comment]
The `SMTPServerDisconnected` here was raised by the server side (the Schannel `80090330` decrypt failure in your Windows mail server logs), not by parsedmarc. SMTP TLS option handling was also overhauled in 10.0.0 (#613). Closing as stale; please open a new issue if you can reproduce on a current release.

---
🤖 Triaged and closed by [Claude Code](https://claude.com/claude-code) at the maintainer's request.
