### ISSUE TITLE
parsedmarc not starting: No module named 'kafka.vendor.six.moves'

### ISSUE THREAD

**Issue by Archetrix** [domainaware/parsedmarc#484]
I've recently rebuild dmarc visualizer (docker-compose build) and now parsedmarc won't start. It exits with code 1 and this stack trace.

`parsedmarc-1     | Traceback (most recent call last):
parsedmarc-1     |   File "/usr/local/bin/parsedmarc", line 5, in <module>
parsedmarc-1     |     from parsedmarc.cli import _main
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/parsedmarc/cli.py", line 20, in <module>
parsedmarc-1     |     from parsedmarc import get_dmarc_reports_from_mailbox, watch_inbox, \
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/parsedmarc/kafkaclient.py", line 6, in <module>
parsedmarc-1     |     from kafka import KafkaProducer
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/__init__.py", line 23, in <module>
parsedmarc-1     |     from kafka.consumer import KafkaConsumer
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/consumer/__init__.py", line 3, in <module>
parsedmarc-1     |     from kafka.consumer.group import KafkaConsumer
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/consumer/group.py", line 13, in <module>
parsedmarc-1     |     from kafka.consumer.fetcher import Fetcher
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/consumer/fetcher.py", line 19, in <module>
parsedmarc-1     |     from kafka.record import MemoryRecords
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/record/__init__.py", line 1, in <module>
parsedmarc-1     |     from kafka.record.memory_records import MemoryRecords, MemoryRecordsBuilder
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/record/memory_records.py", line 27, in <module>
parsedmarc-1     |     from kafka.record.legacy_records import LegacyRecordBatch, LegacyRecordBatchBuilder
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/record/legacy_records.py", line 50, in <module>
parsedmarc-1     |     from kafka.codec import (
parsedmarc-1     |   File "/usr/local/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
parsedmarc-1     |     from kafka.vendor.six.moves import range
parsedmarc-1     | ModuleNotFoundError: No module named 'kafka.vendor.six.moves'
parsedmarc-1 exited with code 1
`

**Comment by Archetrix** [comment]
Nevermind. Old code on new python. I've stopped all and did a git pull on the project. The latest code builds just fine and runs without error
