### ISSUE TITLE
Failing to utf-8 decode message

### ISSUE THREAD

**Issue by dangelovich** [domainaware/parsedmarc#493]
I'm getting an unhelpful error when processing an IMAP mailbox via iCloud:

`$ sudo -u parsedmarc /opt/parsedmarc/venv/bin/parsedmarc -c /etc/parsedmarc.ini --verbose --debug
    INFO:cli.py:1018:Starting parsedmarc
0it [00:00, ?it/s]
   DEBUG:__init__.py:1343:Found 7 messages in DMARC
   DEBUG:__init__.py:1351:Processing 7 messages
   DEBUG:__init__.py:1355:Processing message 1 of 7: UID 124
   ERROR:cli.py:1289:Mailbox Error
Traceback (most recent call last):
  File "/opt/parsedmarc/venv/lib/python3.9/site-packages/parsedmarc/cli.py", line 1271, in _main
    reports = get_dmarc_reports_from_mailbox(
  File "/opt/parsedmarc/venv/lib/python3.9/site-packages/parsedmarc/__init__.py", line 1358, in get_dmarc_reports_from_mailbox
    msg_content = connection.fetch_message(msg_uid)
  File "/opt/parsedmarc/venv/lib/python3.9/site-packages/parsedmarc/mail/imap.py", line 37, in fetch_message
    return self._client.fetch_message(message_id, parse=False)
  File "/opt/parsedmarc/venv/lib/python3.9/site-packages/mailsuite/imap.py", line 261, in fetch_message
    message = raw_msg[msg_key].decode("utf-8", "replace")
KeyError: ''
`

Looks to me like the utf-8 decode failed?
I'm on v8.8.0. Tried adding some extra debug statements to the code, but it didn't reveal much...
Added a print len(raw_msg)
and a for key,value in raw_msg.items() print key, value - just before the Mailbox Error line in imap.py(line 261). This was the extra output, which didn't help me much
`______This is the length: 
1
b'BODY[]' 1
`

**Comment by dangelovich** [comment]
Did some more debugging and found [this suggestion](https://stackoverflow.com/questions/75444763/python-imaplib-fetching-icloud-mail-rfc822-not-working). Tried it and it works.

`/opt/parsedmarc/venv/lib/python3.9/site-packages/mailsuite/imap.py: Line 245
-            #raw_msg = self.fetch(msg_uid, [b'RFC822'])[msg_uid]
+            raw_msg = self.fetch(msg_uid, [b'BODY[]'])[msg_uid]`

I'm guessing iCloud does something abnormal here, but it might be a bug. In any case, a config item to identify an imap server as iCloud or similar could mitigate the issue.

**Comment by dangelovich** [comment]
> [@dangelovich](https://github.com/dangelovich) I'm reviewing old issues. It looks like current versions of mailsuite might handle this. Is that true?

Funny you ask... I recently rebuilt that host and had been trying to figure out how I got parsedmarc working last time! Your comment was the reminder I needed.

The issue still exists, and the fix above still fixes it.

```(venv) [root@utility ~]# sudo -u parsedmarc /opt/parsedmarc/venv/bin/parsedmarc -c /etc/parsedmarc.ini
0it [00:00, ?it/s]
   ERROR:cli.py:1688:Mailbox Error
Traceback (most recent call last):
  File "/opt/parsedmarc/venv/lib/python3.12/site-packages/parsedmarc/cli.py", line 1665, in _main
    reports = get_dmarc_reports_from_mailbox(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/parsedmarc/venv/lib/python3.12/site-packages/parsedmarc/__init__.py", line 1980, in get_dmarc_reports_from_mailbox
    msg_content = connection.fetch_message(message_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/parsedmarc/venv/lib/python3.12/site-packages/parsedmarc/mail/imap.py", line 55, in fetch_message
    return cast(str, self._client.fetch_message(message_id, parse=False))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/parsedmarc/venv/lib/python3.12/site-packages/mailsuite/imap.py", line 290, in fetch_message
    message = raw_msg[msg_key].decode("utf-8", "replace")  # pyright: ignore[reportOptionalMemberAccess, reportAttributeAccessIssue, reportArgumentType]
              ~~~~~~~^^^^^^^^^
KeyError: ''
(venv) [root@utility ~]# vi /opt/parsedmarc/venv/lib/python3.9/site-packages/mailsuite/imap.py
#
# Changed RFC822 to BODY[] - 
#
(venv) [root@utility ~]# sudo -u parsedmarc /opt/parsedmarc/venv/bin/parsedmarc -c /etc/parsedmarc.ini
0it [00:00, ?it/s]
(venv) [root@utility ~]# 
```

Using:
parsedmarc - 9.0.6
mailsuite - 1.11.0

Also still unclear what that '0it [00:00, ?it/s]' output is about.
