### ISSUE TITLE
got an unexpected keyword argument 'ssl'

### ISSUE THREAD

**Issue by arnydo** [domainaware/parsedmarc#60]
Attempting to configure SMTP not to SSL. 

This is the error received:

```
Traceback (most recent call last):
  File "/usr/local/bin/parsedmarc", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/parsedmarc/cli.py", line 435, in _main
    subject=opts.smtp_subject)
TypeError: email_results() got an unexpected keyword argument 'ssl'
```

# Config file
```
[smtp]
host = ***
port = 25
ssl = False
from = ***
to = ***
subject = ParseDMARC Report
```

**Comment by seanthegeek** [comment]
Fixed in 6.1.2. Thanks!
