### ISSUE TITLE
Elasticsearch with username/password hashtag

### ISSUE THREAD

**Issue by rnaccache** [domainaware/parsedmarc#65]
I'm having an issue setting the hosts file under Elasticsearch with credentials.
According to the Docs the host takes the form 

[elasticsearch]
hosts = https://username:password@hostname:port

The issue i noticed is that when the password has a hashtag (#) it seems like the string is escaped 
i.e hosts = https://username:password#001@hostname:port

I get the error:

```
Traceback (most recent call last):
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xq66\AppData\Local\Continuum\anaconda3\Scripts\parsedmarc.exe\__main__.py", line 9, in <module>
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\site-packages\parsedmarc\cli.py", line 330, in _main
    opts.elasticsearch_ssl_cert_path)
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\site-packages\parsedmarc\elastic.py", line 192, in set_hosts
    connections.create_connection(**conn_params)
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\site-packages\elasticsearch_dsl\connections.py", line 66, in create_connection
    conn = self._conns[alias] = Elasticsearch(**kwargs)
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\site-packages\elasticsearch\client\__init__.py", line 188, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\site-packages\elasticsearch\client\__init__.py", line 43, in _normalize_hosts
    if parsed_url.port:
  File "c:\users\xq66\appdata\local\continuum\anaconda3\lib\urllib\parse.py", line 159, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'password'
```

**Comment by seanthegeek** [comment]
Special characters in the username or password must be [URL encoded](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters).

For example:

```
 https://username:password%23001@hostname:port
 ```
