### ISSUE TITLE
TypeError: '>' not supported between instances of 'bytes' and 'int'

### ISSUE THREAD

**Issue by hundeboll** [domainaware/parsedmarc#75]
After parsing existing mails from inbox, the process fails with:
```
Apr 29 11:02:50 first parsedmarc[4544]:    DEBUG:__init__.py:851:IMAP server supports: ['IMAP4REV1', 'SASL-IR', 'LOGIN-REFERRALS', 'ID', 'ENABLE', 'IDLE', 'SORT', 'SORT=DISPLAY', 'THREAD=REFERENCES', 'THREAD=REFS', 'THREAD=ORDEREDSUBJECT', 'MULTIAPPEND', 'URL-PARTIAL', 'CATENATE', 'UNSELECT', 'CHILDREN', 'NAMESPACE', 'UIDPLUS', 'LIST-EXTENDED', 'I18NLEVEL=1', 'CONDSTORE', 'QRESYNC', 'ESEARCH', 'ESORT', 'SEARCHRES', 'WITHIN', 'CONTEXT=SEARCH', 'LIST-STATUS', 'BINARY', 'MOVE', 'SNIPPET=FUZZY', 'LITERAL+', 'NOTIFY', 'SPECIAL-USE']                              
Apr 29 11:03:16 first parsedmarc[4544]: Traceback (most recent call last):
Apr 29 11:03:16 first parsedmarc[4544]:   File "/root/.local/share/virtualenvs/parsedmarc-VwoVDP7B/bin/parsedmarc", line 10, in <module>
Apr 29 11:03:16 first parsedmarc[4544]:     sys.exit(_main())
Apr 29 11:03:16 first parsedmarc[4544]:   File "/root/.local/share/virtualenvs/parsedmarc-VwoVDP7B/lib/python3.7/site-packages/parsedmarc/cli.py", line 596, in _main                                                                                                                    
Apr 29 11:03:16 first parsedmarc[4544]:     strip_attachment_payloads=sa)
Apr 29 11:03:16 first parsedmarc[4544]:   File "/root/.local/share/virtualenvs/parsedmarc-VwoVDP7B/lib/python3.7/site-packages/parsedmarc/__init__.py", line 1679, in watch_inbox                                                                                                        
Apr 29 11:03:16 first parsedmarc[4544]:     if response[0] > 0 and response[1] == b'RECENT':
Apr 29 11:03:16 first parsedmarc[4544]: TypeError: '>' not supported between instances of 'bytes' and 'int'
Apr 29 11:03:19 first parsedmarc[4544]: [19B blob data]
```

This is with parsedmarc version `6.3.4` from pypi.

**Comment by seanthegeek** [comment]
Hi. Please test if the 6.3.6 release resolves this issue.

**Comment by hundeboll** [comment]
Hi, thanks for working on this.

Got another error this time:
```
May 01 13:59:16 first parsedmarc[7139]: [19B blob data]
May 01 13:59:16 first parsedmarc[7139]: Traceback (most recent call last):
May 01 13:59:16 first parsedmarc[7139]:   File "/root/.local/share/virtualenvs/parsedmarc-VwoVDP7B/bin/parsedmarc", line 10, in <module>
May 01 13:59:16 first parsedmarc[7139]:     sys.exit(_main())
May 01 13:59:16 first parsedmarc[7139]:   File "/root/.local/share/virtualenvs/parsedmarc-VwoVDP7B/lib/python3.7/site-packages/parsedmarc/cli.py", line 596, in _main
May 01 13:59:16 first parsedmarc[7139]:     strip_attachment_payloads=sa)
May 01 13:59:16 first parsedmarc[7139]:   File "/root/.local/share/virtualenvs/parsedmarc-VwoVDP7B/lib/python3.7/site-packages/parsedmarc/__init__.py", line 1701, in watch_inbox
May 01 13:59:16 first parsedmarc[7139]:     if int(response[0]) > 0 and response[1] == b'RECENT':
May 01 13:59:16 first parsedmarc[7139]: ValueError: invalid literal for int() with base 10: b'OK'
```

**Comment by seanthegeek** [comment]
Ok. Please try the latest git commit by running

    sudo -H pip3 install -U git+https://github.com/domainaware/parsedmarc.git

If that works, I'll make it an official release.

**Comment by hundeboll** [comment]
Seems to work - no errors, data in elasticsearch, and aggregate report in my personal inbox :)

Thanks!
